apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoho-application-service-deployment
spec:
  replicas: 1 # Number of instances (pods) to run

  selector:
    matchLabels:
      app: zoho-application-service

  template:
    metadata:
      labels:
        app: zoho-application-service

    spec:
      containers:
        - name: zoho-application-service-container
          image: zoho-application-service:{{VERSION}}
          imagePullPolicy: IfNotPresent

          # set limits
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'

          env:
            # common ---------------------
            - name: TZ
              value: Europe/Berlin
            - name: NODE_ENV
              value: production

            # service name
            - name: SERVICE_NAME
              value: zoho-application-service

            # own api ---------------------
            # - name: SERVICE_PORT
            #   value: '3000' # default
            - name: GLOBAL_PREFIX
              value: 'api'
            - name: API_PREFIX
              value: v
            - name: API_VERSION
              value: '1'

            # external route ----------------------------------
            # ZOHO Base-url
            - name: MS_ZOHO_URL
              value: 'http://zoho-service-service.microservices.svc.cluster.local:3000'

            # DEV ------------------------
            - name: ENABLE_SWAGGER
              value: 'true'

          # secrets from .env.local
          envFrom:
            - secretRef:
                name: zoho-application-service-secret

---
# Service -----------------------------------
apiVersion: v1
kind: Service
metadata:
  name: zoho-application-service-service
spec:
  type: NodePort # for DEV
  selector:
    app: zoho-application-service
  ports:
    - protocol: TCP
      name: http
      # nodePort: 30001 # for DEV - The port on the node where external traffic will come in on (requires type NodePort obove)
      port: 3000 # The port of this service
      targetPort: 3000 # The target port on the pod(s) to forward traffic to

