name: 'pdf-servcie-environment'

services:
  # static file server
  nginx:
    container_name: 'nginx'
    image: nginx:1.27.4-alpine
    ports:
      - 8080:80
    volumes:
      - ./html/:/usr/share/nginx/html

  # pdf generator
  gotenberg:
    container_name: 'gotenberg'
    image: gotenberg/gotenberg:8.23.0
    ports:
      - 4000:3000

    # environment:
    #  - LOG_LEVEL=debug
